apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-sjm-18-python-18-3
  janus-idp.io/tekton: test-sjm-18-python-18-3
  backstage.io/kubernetes-id: test-sjm-18-python-18-3
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: test-sjm-18-python-18-3
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
